version: '3'
services:
  nginx:
    image: nginx-img
    container_name: nginx
    build:
      context: src/nginx
      dockerfile: Dockerfile
    ports:
      - 140:140
    networks:
      - incep05
    depends_on:
      - wordpress
  wordpress:
    image: wordpress-img
    container_name: wordpress
    build:
      context: src/wordpress
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - incep05
    # env_file:
    #   - .env
    depends_on:
      - mariadb
  mariadb:
    image: mariadb-img
    container_name: mariadb
    build:
      context: src/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - incep05
    # env_file:
    #   - .env

volumes:
  mariadb-database:
    driver: local
    driver_opts:
networks:
  incep05:
    driver: bridge