version: '3'
services:
  nginx:
    image: nginx-img
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - 443:443
    volumes:
      - wordpress-content:/var/www/html/wordpress
    networks:
      - inception
    restart: always
    depends_on:
      - wordpress
  wordpress:
    image: wordpress-img
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-content:/var/www/html/wordpress
    networks:
      - inception
    restart: always
    depends_on:
      - mariadb
  mariadb:
    image: mariadb-img
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT: ${DB_ROOT}
    volumes:
      - mariadb-database:/var/lib/mysql
    networks:
      - inception
    restart: always

volumes:
  wordpress-content:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tnantaki/data/wordpress
  mariadb-database:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/tnantaki/data/mariadb
networks:
  inception:
    driver: bridge