version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    ports:
      - 8080:80
    volumes:
      - ./client/web:/usr/share/nginx/html
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    ports:
      - 8081:80
    volumes:
      - ./server/web:/usr/share/nginx/html