version: '3'
services:
  nginx:
    image: nginx-img
    container_name: nginx
    build:
      context: src/nginx
      dockerfile: Dockerfile
    ports:
      - 1024:1024
    volumes:
      - wordpress-content:/var/www/html/wordpress
    networks:
      - incep04
    depends_on:
      - wordpress
  wordpress:
    image: wordpress-img
    container_name: wordpress
    build:
      context: src/wordpress
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - wordpress-content:/var/www/html/wordpress
    networks:
      - incep04
    depends_on:
      - mariadb
  mariadb:
    image: mariadb-img
    container_name: mariadb
    build:
      context: src/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT: ${DB_ROOT}
    volumes:
      - mariadb-database:/var/lib/mysql
    networks:
      - incep04

volumes:
  wordpress-content:
    driver: local
  mariadb-database:
    driver: local
networks:
  incep04:
    driver: bridge