version: '3'
services:
  nginx:
    image: nginx-img
    container_name: nginx-con
    build:
      context: src/nginx
      dockerfile: Dockerfile
    ports:
      - 1024:1024
    volumes:
      - wordpress-content:/var/www/html/wordpress
    networks:
      - incep03
    depends_on:
      - wordpress
  wordpress:
    image: wordpress-img
    container_name: wordpress-con
    build:
      context: src/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress-content:/var/www/html/wordpress
    networks:
      - incep03

volumes:
  wordpress-content:
    driver: local
networks:
  incep03:
    driver: bridge
