version: '3'
services:
  nginx:
    image: nginx-img
    container_name: nginx-con
    build:
      context: src/nginx
      dockerfile: Dockerfile
    ports:
      - 100:100
    networks:
      - mos-serve
    depends_on:
      - htmltext
  htmltext:
    image: htmltext-img
    container_name: htmltext-con
    build:
      context: src/htmltext
      dockerfile: Dockerfile
    networks:
      - mos-serve

networks:
  mos-serve:
    driver: bridge